version: '3'

services:
  composer:
    image: 'composer:2'
    volumes:
      - '.:/app'
    user: '1000:1000'

  php:
    image: 'php:8-alpine'
    volumes:
      - '.:/app'
    user: '1000:1000'
    ports:
      - '80:80'
    command: >
      sh -c 'php -S 0.0.0.0:80 -t /app'
