version: '3'

services:
  composer:
    image: 'composer:2'
    volumes:
      - '.:/app'
    user: '1000:1000'

  php:
    build:
      context: './Dockerfiles/apache'
      dockerfile: 'Dockerfile'
    working_dir: '/var/www/html'
    volumes:
      - '.:/var/www/html'
    user: '1000:1000'
    ports:
      - '80:80'
